baseURL = "https://es.shoogle.net/la-rioja/"
languageCode = "es"
title = "La Rioja"
theme = "ln-base"

disableKinds = ["RSS", "robotsTXT"]
enableGitInfo = true

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "la-rioja"

[taxonomies]
  shop = "shops"

